### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by CaptChrisD** [nerves-project/nerves_leds#1]
Should configuration (config.exs) have the key :leds or should it be :nerves_leds or nerves: [leds: ....]??

I am thinking the latter as to avoid collision with other modules that may be used... In this project it may seem trivial, but as we move forward we should stick with one convention

**Comment by ghitchens** [comment]
Good point, I'll investigate at elixirconf the right conventions for this

**Comment by ghitchens** [comment]
0.7.0   It's nerves_leds.   Convention is the module name.
