### ISSUE TITLE
Typo in Hex Docs

### ISSUE THREAD

**Issue by takasehideki** [nerves-project/nerves_leds#17]
I found a typo in Hex Docs.
`:hearbeat` should be `:heartbeat`

https://github.com/nerves-project/nerves_leds/blob/4206b3be7b3a7df743d4e2b72a8afe387f45c1ad/lib/nerves_leds.ex#L54

**Comment by fhunleth** [comment]
Fixed in f3752cebd36c047981838b3407158585a9b133e3. Thanks!

**Comment by fhunleth** [comment]
@ghitchens I fixed the typo above, but it turns out that I don't have permission to update the docs on hex.pm. Could you either push the docs or give me permission?
